/*
 * This source file was generated by the Gradle 'init' task
 */
package ex03_syntax;

public class App {

    public static void main(String[] args) {
        System.out.println("Java 문법2");

        boolean have_money = true;

        if (have_money) {
            System.out.println("택시를 탄다");
        } else {
            System.out.println("걸어간다");
        }

        int money = 9000;

        if (money > 15000) {
            System.out.println("집에까지 가주세요~");
        } else if (money > 6000) {
            System.out.println("중간에 내려주세요~");
        } else {
            System.out.println("걸어갈께요. ㅠㅠ");
        }
    }
}
