spring.application.name=book_ming

# 로그 색상
spring.output.ansi.enabled=always

# 로그 설정
logging.level.root=info

# ===============================
# Oracle DB Settings
# ===============================
spring.datasource.url=jdbc:oracle:thin:@localhost:1521:XE
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.username=studygroup
spring.datasource.password=java12345

# ===============================
# JPA Settings
# ===============================
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect

# 중요: 직접 테이블 만들었으면 none 추천
spring.jpa.hibernate.ddl-auto=none

# SQL 출력
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# LOB 처리 (CLOB 때문에 중요)
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true